apiVersion: v1
kind: Service
metadata:
    name: api-service
spec:
    type: NodePort
    ports:
        - port: 9000
          targetPort: 9000
          nodePort: 31555
    selector:
        component: api
